apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: haproxy-stats
    port: 8050 
    targetPort: 8050  
    protocol: TCP
  type: NodePort